
$(eval $(call addlib,apphelloocaml))

LIBS := $(UK_LIBS)/gcc:$(UK_LIBS)/pthread-embedded:$(UK_LIBS)/newlib:$(UK_LIBS)/ocaml

APPHELLOOCAML_SRCS-y += $(APPHELLOOCAML_BASE)/main.c
APPHELLOOCAML_OBJS-y += $(APPHELLOOCAML_BASE)/program.o


#  ocamlopt ~/.opam/trunk/lib/ocaml/unix.cmxa ocaml.ml -output-obj -o program.o
# 